default: &default
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
  size_estimate_samples: 1000

development:
  <<: *default
  database: cache

test:
  <<: *default
  database: cache

production:
  <<: *default
  database: cache
