default: &default
  store_options:
    max_age: <%= 1.week.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
    expiry_batch_size: 100
  size_estimate_samples: 1000

development:
  <<: *default
  database: cache

test:
  <<: *default
  database: cache

production:
  <<: *default
  database: cache
