default: &default
  send_published_post:
    class: SendSchedulePostJob
    schedule: every minute
  verify_dns:
    class: VerifyDNSRecordsJob
    schedule: every day
  monitor_stuck_posts:
    class: MonitorStuckPostsJob
    schedule: every 10 minutes
  send_automatic_reminders:
    class: SendAutomaticRemindersJob
    schedule: every 5 minutes

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
