name: Herb Lint
permissions:
  contents: read
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Run Herb Linter
        run: bunx @herb-tools/linter
