name: RSpec

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client libpq-dev

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Restore Bootsnap cache
        uses: actions/cache@v4
        with:
          path: tmp/cache
          key: ${{ runner.os }}-bootsnap-${{ hashFiles('.ruby-version', 'Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bootsnap-

      - name: Setup Databases
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          QUEUE_DATABASE_URL: postgres://postgres:postgres@localhost:5432
          CACHE_DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails db:create db:schema:load db:schema:load:queue db:schema:load:cache

      - name: Run tests
        env:
          RAILS_ENV: test
          COVERAGE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'true' || 'false' }}
          ENABLE_BILLING: "true"
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          QUEUE_DATABASE_URL: postgres://postgres:postgres@localhost:5432
          CACHE_DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails spec
